force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <description>This custom object stores lease contract details</description>
    <label>Lease Agreement</label>
    <nameField>
        <label>Lease Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Prevent duplicates</description>
    <label>Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>UI convenience</description>
    <label>PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field define which proprty this lease agreement related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Tenant__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>This Custom Object Stores all property details</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <description>This Custom object stores details of all tenants</description>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeaseAgreementServiceTest.cls
@IsTest
private class LeaseAgreementServiceTest {

    private static Lease_Agreement__c createLease() {

        Property__c property = TestDataFactory.createProperty(true);
        Tenant__c tenant = TestDataFactory.createTenant(true);
        Lease_Agreement__c lease =TestDataFactory.createLease(
                property.Id,
                tenant.Id,
                true
            );
        lease.Tenant__c = tenant.Id;
        update lease;
        return lease;
    }

    private static String getPdfBase64() {
        return EncodingUtil.base64Encode(
            Blob.valueOf('Dummy PDF')
        );
    }

    @IsTest
    static void testGetLeaseAgreement() {
        Lease_Agreement__c lease = createLease();
        Test.startTest();
        LeaseAgreementController.LeaseAgreementDTO dto =
            LeaseAgreementService.getLeaseAgreement(
                lease.Id
            );
        Test.stopTest();
        System.assertEquals(
            lease.Id,
            dto.id
        );
        System.assertEquals(
            lease.Name,
            dto.name
        );
    }

    @IsTest
    static void testGetLeaseAgreement_NullId() {
        try {
            LeaseAgreementService.getLeaseAgreement(null);
            System.assert(false);
        } catch (AuraHandledException ex) {
        }
    }

    @IsTest
    static void testSavePdf() {
        Lease_Agreement__c lease = createLease();
        Test.startTest();
        LeaseAgreementService.savePdf(
            lease.Id,
            'Lease.pdf',
            getPdfBase64()
        );
        Test.stopTest();
        System.assertEquals(1,
            [
                SELECT COUNT()
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :lease.Id
            ]
        );
    }

    @IsTest
    static void testMarkPdfGenerated() {
        Lease_Agreement__c lease = createLease();
        Test.startTest();
        LeaseAgreementService.markPdfGenerated(
            lease.Id
        );
        Test.stopTest();
        lease = [
            SELECT PDF_Generated__c
            FROM Lease_Agreement__c
            WHERE Id = :lease.Id
        ];
        System.assert(
            lease.PDF_Generated__c
        );
    }

    @IsTest
    static void testSendPdfToTenant() {
        Lease_Agreement__c lease = createLease();
        LeaseAgreementService.savePdf(
            lease.Id,
            'Lease.pdf',
            getPdfBase64()
        );
        Test.startTest();
        LeaseAgreementService.sendPdfToTenant(
            lease.Id
        );
        Test.stopTest();
        lease = [
            SELECT Email_Sent__c
            FROM Lease_Agreement__c
            WHERE Id = :lease.Id
        ];
        System.assert(
            lease.Email_Sent__c
        );
    }

    @IsTest
    static void testSendAgreementEmail() {
        Lease_Agreement__c lease = createLease();
        LeaseAgreementService.savePdf(
            lease.Id,
            'Lease.pdf',
            getPdfBase64()
        );
        Test.startTest();
        LeaseAgreementService.sendAgreementEmail(
            lease.Id
        );
        Test.stopTest();
        lease = [
            SELECT Email_Sent__c
            FROM Lease_Agreement__c
            WHERE Id = :lease.Id
        ];
        System.assertEquals(
            true,
            lease.Email_Sent__c
        );
    }

    @IsTest
    static void testSearchLeaseAgreements() {
        createLease();
        LeaseAgreementController.LeaseAgreementSearchRequest req =
            new LeaseAgreementController.LeaseAgreementSearchRequest();
        req.pageNumber = 1;
        req.pageSize = 10;
        req.sortBy = 'Name';
        req.sortDirection = 'ASC';
        Test.startTest();
        LeaseAgreementController.LeaseAgreementSearchResponse response =LeaseAgreementService.getLeaseAgreements(req);
        Test.stopTest();
        System.assertEquals(
            1,
            response.records.size()
        );
        System.assertEquals(
            1,
            response.totalRecords
        );
    }

    @IsTest
    static void testSearchNullRequest() {
        Test.startTest();
        LeaseAgreementController.LeaseAgreementSearchResponse response =
            LeaseAgreementService.getLeaseAgreements(
                null
            );
        Test.stopTest();
        System.assertNotEquals(
            null,
            response
        );
    }

    @IsTest
    static void testMaximumPageLimit() {
        LeaseAgreementController.LeaseAgreementSearchRequest req =
        new LeaseAgreementController.LeaseAgreementSearchRequest();
        req.pageNumber = 100;
        req.pageSize = 50;
        try {
            LeaseAgreementService.getLeaseAgreements(
                req
            );
            System.assert(false);
        } catch (AuraHandledException ex) {
        }
    }

    @IsTest
    static void testSavePdfValidation() {
        Lease_Agreement__c lease = createLease();
        try {
            LeaseAgreementService.savePdf(
                lease.Id,
                'Lease.pdf',
                null
            );
            System.assert(false);
        } catch (AuraHandledException ex) {
        }
    }

    @IsTest
    static void testSendPdfWithoutPdf() {
        Lease_Agreement__c lease = createLease();
        try {
            LeaseAgreementService.sendPdfToTenant(lease.Id);
            System.assert(false);
        } catch (AuraHandledException ex) {
        }
    }
}